"""Curated sample form-library definitions (horizontal; not TREC-licensed content).

TREC/official board PDFs must be uploaded by the design partner. This package
ships a generic multi-party agreement PDF generated at seed time so tenants can
demo library + roles + merge tokens immediately.
"""

from __future__ import annotations

SAMPLE_PURCHASE_AGREEMENT = {
    "library_key": "sample-purchase-agreement",
    "name": "Sample Purchase Agreement",
    "category": "general",
    "description": (
        "Demo multi-party agreement with Buyer / Seller / Agent roles and "
        "shared document-data merge tokens. Replace with your board forms "
        "(e.g. TREC) by uploading the official PDF and cloning this field pattern."
    ),
    "roles": [
        {"key": "buyer", "label": "Buyer", "order": 1},
        {"key": "seller", "label": "Seller", "order": 2},
        {"key": "agent", "label": "Agent", "order": 3},
    ],
    "field_layout": [
        {
            "field_type": "text",
            "page": 1,
            "x": 0.12,
            "y": 0.78,
            "w": 0.55,
            "h": 0.035,
            "required": True,
            "label": "Property address",
            "recipient_index": None,
            "role_key": "",
            "merge_token": "listing.full_address",
            "fill_mode": "document",
            "prefill_editable": True,
        },
        {
            "field_type": "text",
            "page": 1,
            "x": 0.12,
            "y": 0.72,
            "w": 0.28,
            "h": 0.035,
            "required": True,
            "label": "Purchase price",
            "recipient_index": None,
            "role_key": "",
            "merge_token": "deal.price",
            "fill_mode": "document",
            "prefill_editable": True,
        },
        {
            "field_type": "text",
            "page": 1,
            "x": 0.45,
            "y": 0.72,
            "w": 0.28,
            "h": 0.035,
            "required": False,
            "label": "MLS number",
            "recipient_index": None,
            "role_key": "",
            "merge_token": "listing.mls_number",
            "fill_mode": "document",
            "prefill_editable": True,
        },
        {
            "field_type": "text",
            "page": 1,
            "x": 0.12,
            "y": 0.55,
            "w": 0.35,
            "h": 0.035,
            "required": True,
            "label": "Buyer legal name",
            "recipient_index": None,
            "role_key": "",
            "merge_token": "role.buyer.name",
            "fill_mode": "document",
            "prefill_editable": True,
        },
        {
            "field_type": "signature",
            "page": 1,
            "x": 0.12,
            "y": 0.42,
            "w": 0.35,
            "h": 0.06,
            "required": True,
            "label": "Buyer signature",
            "recipient_index": 0,
            "role_key": "buyer",
            "merge_token": "",
            "fill_mode": "signer",
            "prefill_editable": False,
        },
        {
            "field_type": "date",
            "page": 1,
            "x": 0.50,
            "y": 0.42,
            "w": 0.22,
            "h": 0.04,
            "required": True,
            "label": "Buyer date",
            "recipient_index": 0,
            "role_key": "buyer",
            "merge_token": "",
            "fill_mode": "signer",
            "prefill_editable": False,
        },
        {
            "field_type": "text",
            "page": 1,
            "x": 0.12,
            "y": 0.30,
            "w": 0.35,
            "h": 0.035,
            "required": True,
            "label": "Seller legal name",
            "recipient_index": None,
            "role_key": "",
            "merge_token": "role.seller.name",
            "fill_mode": "document",
            "prefill_editable": True,
        },
        {
            "field_type": "signature",
            "page": 1,
            "x": 0.12,
            "y": 0.17,
            "w": 0.35,
            "h": 0.06,
            "required": True,
            "label": "Seller signature",
            "recipient_index": 1,
            "role_key": "seller",
            "merge_token": "",
            "fill_mode": "signer",
            "prefill_editable": False,
        },
        {
            "field_type": "date",
            "page": 1,
            "x": 0.50,
            "y": 0.17,
            "w": 0.22,
            "h": 0.04,
            "required": True,
            "label": "Seller date",
            "recipient_index": 1,
            "role_key": "seller",
            "merge_token": "",
            "fill_mode": "signer",
            "prefill_editable": False,
        },
    ],
}

LIBRARY_FORMS = [SAMPLE_PURCHASE_AGREEMENT]
