# Generated by Django 5.2.16 on 2026-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_next_follow_up_at_contact_stage_contact_tags_and_more'),
        ('tenants', '0008_website_charfield'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cadenceenrollment',
            name='uniq_active_cadence_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='listing',
            name='uniq_listing_mls_per_tenant',
        ),
        migrations.AlterField(
            model_name='listing',
            name='mls_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('tenant', 'mls_number'), name='uniq_listing_mls_per_tenant'),
        ),
    ]
