# Generated by Django 5.2.16 on 2026-07-15 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_cadenceenrollment_uniq_active_cadence_enrollment_and_more'),
        ('envelopes', '0006_field_recipient_nullable'),
        ('tenants', '0009_listings_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadencestep',
            name='cadence',
        ),
        migrations.RemoveField(
            model_name='cadenceenrollment',
            name='cadence',
        ),
        migrations.RemoveField(
            model_name='cadenceenrollment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='cadenceenrollment',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='cadencestep',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('envelope_sent', 'Envelope sent'), ('envelope_signed', 'Envelope signed'), ('envelope_completed', 'Envelope completed'), ('note', 'Note'), ('follow_up', 'Follow-up'), ('plan_email', 'Follow-up plan email'), ('cadence_email', 'Cadence email')], max_length=40),
        ),
        migrations.CreateModel(
            name='FollowUpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('stalled', 'Signer idle after send'), ('declined', 'Recipient declined'), ('completed', 'Envelope completed')], default='stalled', max_length=20)),
                ('idle_hours', models.PositiveIntegerField(default=48, help_text='For stalled plans: hours after invite before the plan starts.')),
                ('create_agent_handoff', models.BooleanField(default=False, help_text='Create a Follow-up task after the last email.')),
                ('handoff_title', models.CharField(blank=True, default='Call signer — stalled packet', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpPlanEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('current_step_order', models.PositiveIntegerField(default=1)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_plan_enrollments', to='contacts.contact')),
                ('envelope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_enrollments', to='envelopes.envelope')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='contacts.followupplan')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_enrollments', to='envelopes.recipient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_days', models.PositiveIntegerField(help_text='Days after plan start when this email is due.')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Email body. Placeholders: {{recipient_name}}, {{envelope_title}}, {{sign_link}}, {{listing_address}}, {{contact_first_name}}, {{contact_full_name}}.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='contacts.followupplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Cadence',
        ),
        migrations.DeleteModel(
            name='CadenceEnrollment',
        ),
        migrations.DeleteModel(
            name='CadenceStep',
        ),
    ]
