# Generated by Django 5.2.16 on 2026-07-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envelopes', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('consent_accepted', 'Consent accepted'), ('field_completed', 'Field completed'), ('signed', 'Signed'), ('declined', 'Declined'), ('voided', 'Voided'), ('completed', 'Completed'), ('reminded', 'Reminded'), ('downloaded', 'Downloaded')], max_length=40)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consent_version', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='envelopes.envelope')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='envelopes.recipient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['envelope', 'created_at'], name='audit_audit_envelop_a1941d_idx')],
            },
        ),
    ]
