# Generated by Django 5.2.16 on 2026-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('consent_accepted', 'Consent accepted'), ('field_completed', 'Field completed'), ('signed', 'Signed'), ('declined', 'Declined'), ('voided', 'Voided'), ('completed', 'Completed'), ('reminded', 'Reminded'), ('downloaded', 'Downloaded'), ('retention_purged', 'Retention purged')], max_length=40),
        ),
    ]
