# Generated by Django 5.2.16 on 2026-07-14 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_template_is_active'),
        ('tenants', '0008_website_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(blank=True, default='general', max_length=64),
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_library',
            field=models.BooleanField(default=False, help_text='Curated form-library entry (cloneable starting point).'),
        ),
        migrations.AddField(
            model_name='template',
            name='library_key',
            field=models.CharField(blank=True, help_text='Stable key for seeded library forms (empty for user templates).', max_length=128),
        ),
        migrations.AddField(
            model_name='template',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('library_key', ''), _negated=True), fields=('tenant', 'library_key'), name='uniq_template_library_key_per_tenant'),
        ),
    ]
