# Generated by Django 5.2.16 on 2026-07-14 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_template_category_template_description_and_more'),
        ('tenants', '0008_website_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='template',
            name='uniq_template_library_key_per_tenant',
        ),
        migrations.AlterField(
            model_name='template',
            name='library_key',
            field=models.CharField(blank=True, help_text='Stable key for seeded library forms (null for user templates).', max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('tenant', 'library_key'), name='uniq_template_library_key_per_tenant'),
        ),
    ]
