# Generated by Django 5.2.16 on 2026-07-25 19:21

import apps.common.upload_paths
import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_template_uniq_template_library_key_per_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=apps.common.upload_paths.TenantDatedUploadTo('documents'), validators=[apps.documents.models.validate_pdf]),
        ),
    ]
