# Generated by Django 5.2.16 on 2026-07-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='esign_acknowledgement',
            field=models.TextField(default='By continuing, you agree to conduct this transaction electronically, to receive records electronically, and that your electronic signature is legally binding. You may request a paper copy and withdraw consent by contacting the sender.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='esign_acknowledgement_version',
            field=models.CharField(default='2026-01', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_icons/'),
        ),
    ]
