# Generated by Django 5.2.16 on 2026-07-13 14:55

from django.db import migrations, models


LEGACY = (
    "By continuing, you agree to conduct this transaction electronically, "
    "to receive records electronically, and that your electronic signature "
    "is legally binding. You may request a paper copy and withdraw consent "
    "by contacting the sender."
)


def upgrade_legacy_acknowledgements(apps, schema_editor):
    from apps.tenants.esign_disclosure import (
        DEFAULT_ESIGN_ACKNOWLEDGEMENT,
        DEFAULT_ESIGN_ACKNOWLEDGEMENT_VERSION,
    )

    Tenant = apps.get_model("tenants", "Tenant")
    for tenant in Tenant.objects.all():
        if (tenant.esign_acknowledgement or "").strip() == LEGACY:
            tenant.esign_acknowledgement = DEFAULT_ESIGN_ACKNOWLEDGEMENT
            tenant.esign_acknowledgement_version = DEFAULT_ESIGN_ACKNOWLEDGEMENT_VERSION
            tenant.save(
                update_fields=["esign_acknowledgement", "esign_acknowledgement_version"]
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="esign_acknowledgement",
            field=models.TextField(
                default=(
                    "ELECTRONIC RECORDS AND SIGNATURES DISCLOSURE\n\n"
                    "Please read this disclosure carefully before continuing. By checking the box\n"
                    "and selecting Continue, you affirmatively consent to use electronic records\n"
                    "and electronic signatures for this transaction under the Electronic Signatures\n"
                    "in Global and National Commerce Act (E-SIGN Act) and the applicable Uniform\n"
                    "Electronic Transactions Act (UETA).\n\n"
                    "1. Scope of consent\n"
                    "Your consent covers the documents in this envelope, related notices, and other\n"
                    "records provided electronically in connection with this transaction (including\n"
                    "completion notices and downloadable copies of signed documents).\n\n"
                    "2. Intent and legal effect\n"
                    "Your electronic signature (including typed or drawn signatures and initials)\n"
                    "shows your intent to sign and is legally binding to the same extent as a\n"
                    "handwritten signature under applicable law.\n\n"
                    "3. Hardware and software requirements\n"
                    "To access and retain these electronic records you need:\n"
                    "• A device with an internet connection\n"
                    "• A current web browser (such as Chrome, Firefox, Safari, or Edge)\n"
                    "• Software that can view and download Portable Document Format (PDF) files\n\n"
                    "4. Ability to access electronic records\n"
                    "By continuing, you confirm that you can access and retain PDF documents using\n"
                    "the hardware and software described above.\n\n"
                    "5. Paper copies\n"
                    "You may request a paper (non-electronic) copy of these records by contacting\n"
                    "the sender of this envelope (or the workspace that sent it) using the email\n"
                    "address or other contact information in the invitation. The sender may charge\n"
                    "a reasonable fee for paper copies if permitted by law and their policy.\n\n"
                    "6. Withdrawing consent\n"
                    "You may withdraw your consent to receive electronic records by contacting the\n"
                    "sender before you complete your signature. Withdrawal is prospective only: it\n"
                    "does not affect the validity of electronic records or signatures already given\n"
                    "for this transaction. If you withdraw before signing, the sender may provide\n"
                    "paper records or cancel the transaction according to their process.\n\n"
                    "7. Updating your contact information\n"
                    "To update the email address used for electronic delivery of records related to\n"
                    "this transaction, contact the sender promptly so future notices reach you.\n\n"
                    "8. Obtaining and retaining copies\n"
                    "After this envelope is completed, you may download the signed PDF and the\n"
                    "Certificate of Completion using the link in your invitation or completion\n"
                    "email (no account required while the link remains valid). You may also request\n"
                    "copies from the sender. Retention of completed records on the platform is\n"
                    "controlled by the sending workspace; keep your own copies for your records.\n\n"
                    "9. Questions\n"
                    "If you have questions about this disclosure or need assistance accessing these\n"
                    "records, contact the sender of this envelope.\n"
                )
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="esign_acknowledgement_version",
            field=models.CharField(default="2026-07", max_length=32),
        ),
        migrations.RunPython(upgrade_legacy_acknowledgements, noop_reverse),
    ]
