# Generated by Django 5.2.16 on 2026-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='document_retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days to keep signed PDFs and certificates after completion. Blank keeps forever.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='paper_copy_fee_policy',
            field=models.TextField(blank=True, help_text='Optional policy shown to signers about paper-copy fees.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reminder_interval_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reminder_max_count',
            field=models.PositiveIntegerField(default=0, help_text='Maximum automatic reminders per signer. 0 means unlimited.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sender_support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sender_support_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
