# Generated by Django 5.2.16 on 2026-07-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_workspace_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
