# Generated by Django 5.2.16 on 2026-07-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_website_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='listings_enabled',
            field=models.BooleanField(default=False, help_text='Show Prefill records (Listings) for merge fields on envelopes.'),
        ),
    ]
