# Generated by Django 5.2.16 on 2026-07-20 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_email_template_lifecycle_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOpsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('provision', 'Provision tenant'), ('suspend', 'Suspend tenant'), ('reactivate', 'Reactivate tenant'), ('update', 'Update tenant'), ('invite', 'Invite admin'), ('invite_resend', 'Resend invite'), ('invite_revoke', 'Revoke invite'), ('demo_reset', 'Reset demo workspace'), ('media_audit', 'Media orphan audit'), ('media_delete', 'Delete media orphans'), ('form_seed', 'Seed form library'), ('support_snapshot', 'View support snapshot')], db_index=True, max_length=64)),
                ('tenant_slug', models.SlugField(blank=True, max_length=63)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_ops_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_ops_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
