# Generated by Django 5.2.16 on 2026-07-25 19:21

import apps.common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_password_reset_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.upload_paths.TenantBrandingUploadTo('icon')),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.upload_paths.TenantBrandingUploadTo('logo')),
        ),
    ]
