# Generated by Django 5.2.16 on 2026-07-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='consent_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='consent_text_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='recipient',
            name='consent_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='consent_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='recipient',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
