# Generated by Django 5.2.16 on 2026-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0002_esign_ueta_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='retention_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
