# Generated by Django 5.2.16 on 2026-07-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_next_follow_up_at_contact_stage_contact_tags_and_more'),
        ('envelopes', '0003_esign_policy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelopes', to='contacts.listing'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='merge_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='field',
            name='merge_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='recipient',
            name='role_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
