# Generated by Django 5.2.16 on 2026-07-15 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_follow_up_plans'),
        ('envelopes', '0006_field_recipient_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='follow_up_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelopes', to='contacts.followupplan'),
        ),
    ]
