# Generated by Django 5.2.16 on 2026-07-25 19:21

import apps.common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0007_follow_up_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.upload_paths.TenantDatedUploadTo('certificates')),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.common.upload_paths.TenantDatedUploadTo('signed')),
        ),
        migrations.AlterField(
            model_name='signatureasset',
            name='image',
            field=models.ImageField(upload_to=apps.common.upload_paths.TenantDatedUploadTo('signatures')),
        ),
    ]
