# Generated by Django 5.2.16 on 2026-08-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_archive_platform_library_templates'),
        ('envelopes', '0010_recipient_blank_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='library_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_envelopes', to='documents.document'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='library_document_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_envelopes', to='documents.documentversion'),
        ),
    ]
